#ifndef __VHIDMINI_IOCTL_H__
#define __VHIDMINI_IOCTL_H__

#include <initguid.h>

/* ea8ff883-45f3-4463-b2a8-565ca87dce9f */
DEFINE_GUID(GUID_DEVINTERFACE_VHIDMINI, 0xea8ff883, 0x45f3, 0x4463, 0xb2, 0xa8, 0x56, 0x5c, 0xa8, 0x7d, 0xce, 0x9f);

#define FILE_DEVICE_VHIDMINI 0x8000

#define IOCTL_VHIDMINI_KEY_EVENT CTL_CODE(FILE_DEVICE_VHIDMINI, 0x800, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_VHIDMINI_MOVE_EVENT CTL_CODE(FILE_DEVICE_VHIDMINI, 0x801, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_VHIDMINI_BUTTON_EVENT CTL_CODE(FILE_DEVICE_VHIDMINI, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_VHIDMINI_WHEEL_EVENT CTL_CODE(FILE_DEVICE_VHIDMINI, 0x803, METHOD_BUFFERED, FILE_WRITE_ACCESS)

typedef struct _VHID_KEY_EVENT {
    UCHAR KeyCode;   // code HID (ex: 0x04 = A)
    UCHAR Pressed;   // 1 = down, 0 = up
} VHID_KEY_EVENT, *PVHID_KEY_EVENT;

typedef struct _VHID_MOUSE_MOVE {
    CHAR DeltaX;
    CHAR DeltaY;
} VHID_MOUSE_MOVE, *PVHID_MOUSE_EVENT;

typedef struct _VHID_MOUSE_BUTTON {
    UCHAR ButtonMask;   // bit0=left, bit1=right, bit2=middle
} VHID_MOUSE_BUTTON, *PVHID_MOUSE_BUTTON;

#endif //__VHIDMINI_IOCTL_H__
